### PR TITLE
fix: (ement-room-image-show) pass frame parameters

### PR DESCRIPTION
**Pull request by progfolio**

### CODE REVIEW

**Comment by progfolio** [comment]
Sorry..."forg.el" made it too easy to fat finger this.

**Comment by progfolio** [comment]
Come to think of it, why not just skip the ACTION argument and let the user decide?:

```emacs-lisp
(defun ement-room-image-show (pos)
  "Show image at POS in a new buffer."
  (interactive "d")
  (pcase-let* ((ement-event (ewoc-data (ewoc-locate ement-ewoc pos)))
               ((cl-struct ement-event id) ement-event)
               (buffer-name (format "*Ement image: %s*" id)))
    (unless (get-buffer buffer-name)
      (let ((image (copy-sequence (get-text-property pos 'display))))
        (when (fboundp 'imagemagick-types)
          ;; Only do this when ImageMagick is supported.
          ;; FIXME: When requiring Emacs 27+, remove this (I guess?).
          (setf (image-property image :type) 'imagemagick))
        (setf (image-property image :scale) 1.0
              (image-property image :max-width) nil
              (image-property image :max-height) nil)
        (with-current-buffer (get-buffer-create buffer-name)
          (erase-buffer)
          (insert-image image)
          (image-mode))))
    (pop-to-buffer buffer-name)))
```

**Comment by alphapapa** [comment]
I think the current frame parameters should be the default, because I think most users will want that (to be able to see as much of a large image as possible), and no one will want to have to edit `display-buffer-alist` to achieve it.

So I still think [this](https://github.com/alphapapa/ement.el/issues/223#issuecomment-1732821966).

**Comment by progfolio** [comment]
Won't have time to rework the patch in foreseeable future. Feel free to modify or discard.

**Comment by alphapapa** [comment]
Merged as-is.  It's an improvement anyway.  Thanks.

**Pull request closed without merging**
