### PR TITLE
(ement-room-image-keymap) Inherit from image-map

### PR DESCRIPTION
**Pull request by vizs**
Continuation of #39.  I've been using this patch for a while now and no issues so far but note that I don't have images enabled for anything other messages (no avatars, room images, etc.) so there may be other issues that I do not know of.

### CODE REVIEW

**Comment by alphapapa** [comment]
This may be a good change, but it does more than change the keymap.  :)

Also, if it's necessary to leave a comment explaining something, please try to make it self-contained rather than referring to a GitHub issue (that should generally only be done if the explanation is long or requires conversational context).  Or if it's in-between those lengths, you could put it in the commit message.

**Comment by vizs** [comment]
I decided to go in between since someone might be interested in the (slightly) detailed analysis.

**Comment by alphapapa** [comment]
@vizs Do you still plan to work on this?  i.e. since it changes more than what is mentioned in the commit message, it should be split into separate commits and PRs.

**Comment by vizs** [comment]
This is basically done AFAIR.  I'm running ement with these modifications and haven't had any issues so far.  I will look into splitting these into separate PRs/commits sometime next week.

**Comment by alphapapa** [comment]
Thanks.

**Pull request merged**
