### PR TITLE
Update README.org to mention community fork of Pantalaimon

### PR DESCRIPTION
**Pull request by chookity-pokk**
Small update to the README to mention the community fork of Pantalaimon.

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi @chookity-pokk, I'll be glad to do this, but first, is there any chance of contributing these fixes upstream, or perhaps transferring maintainership?  It seems like that might be in the best interest of users, to avoid confusion and having to choose between forks.  If that's not an option, then we can mention both in the readme.

**Comment by chookity-pokk** [comment]
@alphapapa The only reason I haven't upstreamed the changes is because their last commit was almost 18 months ago and they have several [PR's open](https://github.com/matrix-org/pantalaimon/pulls) that they haven't commented on or looked at merging so I figured it was just a waste of time. 

I'm not entirely sure what you mean by transferring maintainership in this context.

**Comment by alphapapa** [comment]
@chookity-pokk By transferring maintainership I mean that someone else who's interested could become the official maintainer of the software, either on that repo or on a fork, if the existing maintainers are willing.

Since they aren't active on the GitHub tracker, would you be willing to email a few of the apparent maintainers, to ask them about it?  That is, if you are willing to consider maintaining the software more officially, rather than just merging the occasional patch.  :)  If you do just want to offer some patches now and then, that's fine too; I don't mean to imply any obligation on your part.  I just think it would be good to be clear about their and your intentions before starting to publicize an alternative source.

**Comment by chookity-pokk** [comment]
Okay, I get what you are saying by maintainership transfer. I will email some of their maintainers today and keep you updated. It definitely would be nice to have things in the same repo. 

Fingers crossed I'll have an answer soon enough!

**Comment by chookity-pokk** [comment]
Closing since I've been added as a maintainer to Pantalaimon.

**Comment by alphapapa** [comment]
> Closing since I've been added as a maintainer to Pantalaimon.

That's great news!  Thanks for your work on that.

**Pull request closed without merging**
